use ethAddr as destination in deposit flow
InjectiveLabs/peggy pull request #2
Opened 2021-01-17 02:47 UTC by mankenavenkatesh

2021-01-24 17:52 UTC, albertchon requested changes

2021-01-24 17:52 UTC, albertchon commented on module/x/peggy/client/cli/tx.go
> +			cliCtx, err := client.GetClientTxContext(cmd)
Don't you need the client context from the cmd? i.e. you could do
```
			cliCtx := client.GetClientContextFromCmd(cmd)
			cliCtx, err := client.GetClientTxContext(cmd)
```

same goes for the other CLI tx cmd's

2021-01-24 17:52 UTC, albertchon commented on module/x/peggy/keeper/attestation_handler.go
> +			destAdd, err := sdk.AccAddressFromBech32(claim.CosmosReceiver)
`destAddr` would be a better name imo

2021-01-24 17:52 UTC, albertchon commented on module/x/peggy/keeper/attestation_handler.go
> +		} else {
seems like everything besides the coin selection and amount determination is repeated logic right? Would be good to DRY it up then

2021-01-24 17:52 UTC, albertchon commented on module/x/peggy/keeper/pool.go
> +	if _, err := types.ValidatePeggyCoin(totalAmount); err != nil && totalAmount.Denom != "inj" {
I think the logic here doesn't make sense.

Let's say the `types.types.ValidatePeggyCoin(totalAmount);(totalAmount);` returns an error but the`totalAmount.Denom` is not "inj".

This would result in (true && false) = false which means the logic would proceed, but it shouldn't since it returned an error in the `types.ValidatePeggyCoin(totalAmount);`

2021-01-25 04:22 UTC, mankenavenkatesh commented on module/x/peggy/keeper/attestation_handler.go
> +		} else {
For inj tokens, we are using mint module account in entire logic. and peggy module account for peggy tokens.

So better to keep it independent.

2021-01-25 04:27 UTC, mankenavenkatesh commented on module/x/peggy/keeper/pool.go
> +	if _, err := types.ValidatePeggyCoin(totalAmount); err != nil && totalAmount.Denom != "inj" {
`totalAmount.Denom != "inj"` is true.  so It would result in (true && true) and logic won't proceed.


so basically, the logic should be executed if it is either `inj` or `Peggy` coin. 
It should throw error if it is none of these coin types.

2021-01-25 04:30 UTC, mankenavenkatesh commented on module/x/peggy/client/cli/tx.go
> +			cliCtx, err := client.GetClientTxContext(cmd)
It's being done inside `GetClientTxContext`.
``
func GetClientTxContext(cmd *cobra.Command) (Context, error) {
	ctx := GetClientContextFromCmd(cmd)
	return readTxCommandFlags(ctx, cmd.Flags())
}
``

2021-01-26 14:39 UTC, merged